### ISSUE TITLE
ipk file for brcm63xx

### ISSUE THREAD

**Issue by crdlight** [adde88/reaver-1.6.1-openwrt#1]
Hi,
Can you share with me the reaver ipk file for brcm63xx.
Thak you

**Comment by adde88** [comment]
Hi, the IPK's in my repos are compiled for ar71xx (wifi pineapples).

But, you can use the Makefiles to compile it yourself for whatever architecture you want with the OpenWRT SDK. 
SDK for brcm63xx can be found on https://downloads.openwrt.org

[Latest SDK](https://downloads.openwrt.org/snapshots/targets/brcm63xx/generic/openwrt-sdk-brcm63xx-generic_gcc-7.4.0_musl.Linux-x86_64.tar.xz)
